runtime: nodejs18

service: default

handlers:
    - url: /.*
      script: auto

env_variables:
    SERVER_URL: $SERVER_URL
    PERSONAL_ACCESS_TOKEN: $PERSONAL_ACCESS_TOKEN
    REPOSITORY: $REPOSITORY
    USER_AGENT: $USER_AGENT
    OWNER: $OWNER
    ARCHIVE_PURCHASED_PHOTOS_FUNCTION_URL: $ARCHIVE_PURCHASED_PHOTOS_FUNCTION_URL
    PHOTOS_BUCKET: $PHOTOS_BUCKET
    PUBLIC_PHOTOS_BUCKET: $PUBLIC_PHOTOS_BUCKET
    PHOTO_CAROUSEL_BUCKET: $PHOTO_CAROUSEL_BUCKET
    NATURE_SHOWCASE_BUCKET: $NATURE_SHOWCASE_BUCKET
    ANIMALS_SHOWCASE_BUCKET: $ANIMALS_SHOWCASE_BUCKET
    ARCHITECTURAL_SHOWCASE_BUCKET: $ARCHITECTURAL_SHOWCASE_BUCKET
    PORTRAIT_SHOWCASE_BUCKET: $PORTRAIT_SHOWCASE_BUCKET
    WEDDING_SHOWCASE_BUCKET: $WEDDING_SHOWCASE_BUCKET
    SPORT_SHOWCASE_BUCKET: $SPORT_SHOWCASE_BUCKET
    SECRET_KEY: $SECRET_KEY
    WEBHOOK_SECRET: $WEBHOOK_SECRET
