name: Deploy Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Setup GCloud SDK
        uses: google-github-actions/deploy-cloud-functions@v1

      - name: Deploy compressPublicPhotos
        with:
        run: |
          gcloud functions deploy name-of-function \
            --gen2 \
            --region=europe-north1 \
            --runtime=nodejs18 \
            --source=cloud functions \
            --entry-point=compressPhotos
            