name: Deploy to Google Cloud

on:
    push:
        branches:
            - main

jobs:
    Deploy-Cloud-Functions:
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

            - name: Setup GCloud SDK
              uses: google-github-actions/setup-gcloud@v1

            - name: Deploy compressPublicPhotos
              run: |
                  gcloud functions deploy compressPublicPhotos \
                  --gen2 \
                  --region=europe-north1 \
                  --runtime=nodejs18 \
                  --source=${{ github.workspace }}/cloud_functions/compressPublicPhotos \
                  --entry-point=compressPhoto \
                  --trigger-event-filters=bucket=${{ secrets.GCLOUD_PHOTOS_BUCKET }} \
                  --trigger-event-filters=type=google.cloud.storage.object.v1.finalized \
                  --project=${{ secrets.GCLOUD_PROJECT_ID }}

            - name: Deploy deletePublicPhotos
              run: |
                  gcloud functions deploy deletePublicPhotos \
                  --gen2 \
                  --region=europe-north1 \
                  --runtime=nodejs18 \
                  --source=${{ github.workspace }}/cloud_functions/deletePublicPhotos \
                  --entry-point=deletePhoto \
                  --trigger-event-filters=bucket=${{ secrets.GCLOUD_PHOTOS_BUCKET }} \
                  --trigger-event-filters=type=google.cloud.storage.object.v1.deleted \
                  --project=${{ secrets.GCLOUD_PROJECT_ID }}
