name: Deploy Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: beta

      - name: Deploy compressPublicPhotos
        run: |
          gcloud beta functions deploy compressPublicPhotos \
            --gen2 \
            --region=europe-north1 \
            --runtime=nodejs18 \
            --source=cloud functions \
            --entry-point=compressPhotos
