name: Format

on:
  push:
    branches:
      - main
      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Format code with Prettier
        run: npm run testFormat

      - name: Commit changes if needed
        if failure()
        run: npm run format
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}