name: Format

on:
  push:
    branches:
      - main
      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Commit changes if needed
        env:
          APP_ID: ${{ secrets.WORKFLOW_AUTHENTICATOR_APP_ID }}
          PRIVATE_KEY: ${{ secrets.WORKFLOW_AUTHENTICATOR_PRIVATE_KEY }}
          INSTALLATION_ID: ${{ secrets.WORKFLOW_AUTHENTICATOR_INSTALLATION_ID }}
        run: |
          npx prettier .prettierrc --write .
          npx @octokit/auth-app -a $APP_ID -k $PRIVATE_KEY -I $INSTALLATION_ID
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Run Prettier"
          git push